version: '3'

services:
  flask:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/opt/article_explorer
    ports:
      - 0.0.0.0:7777:5000

  db:
    image: "postgres"
    env_file:
      - db.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  postgres_data:
