version: '3.7'

volumes:
   pg_data:

services:
  flask:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/opt/article_explorer
      - ./logs:/opt/logs
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/pg_data
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.8
    volumes:
      - ./redis_data:/var/lib/redis/data

  celery:
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    env_file:
      - .env
    volumes:
      - ./logs:/opt/logs
    depends_on:
      - db
      - redis
